{
    "count": 10,
    "next": null,
    "previous": null,
    "results": [
        {
            "author_name": "Álvaro Justen",
            "author_url": "https://twitter.com/turicas",
            "code_url": "https://github.com/theinterceptbr/portaldatransparencia",
            "description": "Pagamentos para aquisição e contratação de obras e compras governamentais, dentre outros, realizados pelos órgãos e entidades da Administração Pública Federal, que executam as despesas pelo Sistema Integrado de Administração Financeira do Governo Federal (Siafi).",
            "id": "https://brasil.io/api/dataset/gastos-diretos/",
            "license_name": "Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)",
            "license_url": "https://creativecommons.org/licenses/by-sa/4.0/",
            "name": "Gastos Diretos do Governo Federal",
            "slug": "gastos-diretos",
            "source_name": "Portal da Transparência",
            "source_url": "http://www.portaldatransparencia.gov.br/downloads/mensal.asp?c=GastosDiretos"
        },
        {
            "author_name": "Álvaro Justen",
            "author_url": "https://twitter.com/turicas",
            "code_url": "https://github.com/turicas/eleicoes-brasil",
            "description": "Dados das eleições brasileiras, desde 1996, capturados do TSE, como: filiados a partidos, candidatos e votação. Note que nem todos os arquivos estão completos - verifique no TSE os que estão completos.",
            "id": "https://brasil.io/api/dataset/eleicoes-brasil/",
            "license_name": "Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)",
            "license_url": "https://creativecommons.org/licenses/by-sa/4.0/",
            "name": "Eleições Brasil",
            "slug": "eleicoes-brasil",
            "source_name": "Tribunal Superior Eleitoral do Brasil (TSE)",
            "source_url": "http://www.tse.jus.br/eleitor-e-eleicoes/estatisticas/repositorio-de-dados-eleitorais-1"
        },
        {
            "author_name": "Álvaro Justen",
            "author_url": "https://twitter.com/turicas",
            "code_url": "https://github.com/turicas/genero-nomes",
            "description": "Classificação de gênero em nomes brasileiros, com base em dados do CENSO de 2010.",
            "id": "https://brasil.io/api/dataset/genero-nomes/",
            "license_name": "Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)",
            "license_url": "https://creativecommons.org/licenses/by-sa/4.0/",
            "name": "Gênero dos Nomes",
            "slug": "genero-nomes",
            "source_name": "Instituto Brasileiro de Geografia e Estatística (IBGE)",
            "source_url": "https://censo2010.ibge.gov.br/nomes/"
        },
        {
            "author_name": "Álvaro Justen",
            "author_url": "https://twitter.com/turicas",
            "code_url": "https://github.com/turicas/socios-brasil",
            "description": "Quadros societários e de administradores das pessoas jurídicas brasileiras.",
            "id": "https://brasil.io/api/dataset/socios-brasil/",
            "license_name": "Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)",
            "license_url": "https://creativecommons.org/licenses/by-sa/4.0/",
            "name": "Sócios das Empresas Brasileiras",
            "slug": "socios-brasil",
            "source_name": "Receita Federal do Brasil",
            "source_url": "http://idg.receita.fazenda.gov.br/orientacao/tributaria/cadastros/cadastro-nacional-de-pessoas-juridicas-cnpj/dados-abertos-do-cnpj"
        },
        {
            "author_name": "Álvaro Justen",
            "author_url": "https://twitter.com/turicas",
            "code_url": "https://github.com/turicas/salarios-magistrados",
            "description": "Pagamentos efetuados aos magistrados para cumprimento da Lei n. 12.527, de 18 de novembro de 2011 (Lei de Acesso à Informação) e da Resolução n. 215, de 16 de dezembro de 2015.",
            "id": "https://brasil.io/api/dataset/salarios-magistrados/",
            "license_name": "Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)",
            "license_url": "https://creativecommons.org/licenses/by-sa/4.0/",
            "name": "Salários dos Magistrados",
            "slug": "salarios-magistrados",
            "source_name": "Conselho Nacional de Justiça do Brasil (CNJ)",
            "source_url": "http://www.cnj.jus.br/transparencia/remuneracao-dos-magistrados"
        },
        {
            "author_name": "Álvaro Justen",
            "author_url": "https://twitter.com/turicas",
            "code_url": "https://github.com/turicas/cursos-prouni",
            "description": "Quantidade de vagas, mensalidade e notas de corte do PROUNI 2018.",
            "id": "https://brasil.io/api/dataset/cursos-prouni/",
            "license_name": "Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)",
            "license_url": "https://creativecommons.org/licenses/by-sa/4.0/",
            "name": "Cursos e notas de corte do PROUNI 2018",
            "slug": "cursos-prouni",
            "source_name": "Ministério da Educação do Brasil (MEC)",
            "source_url": "http://prounialuno.mec.gov.br/consulta/publica/"
        },
        {
            "author_name": "Álvaro Justen",
            "author_url": "https://twitter.com/turicas",
            "code_url": "https://github.com/Correio24horas/balneabilidade-bahia",
            "description": "Condição de balneabilidade das praias da costa baiana, retirados dos boletins semanais do INEMA.",
            "id": "https://brasil.io/api/dataset/balneabilidade-bahia/",
            "license_name": "Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)",
            "license_url": "https://creativecommons.org/licenses/by-sa/4.0/",
            "name": "Estado da balneabilidade da costa baiana",
            "slug": "balneabilidade-bahia",
            "source_name": "Instituto do Meio Ambiente e Recursos Hídricos da Bahia (INEMA)",
            "source_url": "http://balneabilidade.inema.ba.gov.br/index.php/relatoriodebalneabilidade/boletim"
        },
        {
            "author_name": "Álvaro Justen",
            "author_url": "https://twitter.com/turicas",
            "code_url": "https://github.com/turicas/gastos-deputados",
            "description": "Gastos parlamentares registrados na Câmara dos Deputados",
            "id": "https://brasil.io/api/dataset/gastos-deputados/",
            "license_name": "Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)",
            "license_url": "https://creativecommons.org/licenses/by-sa/4.0/",
            "name": "Gastos dos deputados",
            "slug": "gastos-deputados",
            "source_name": "Câmara dos Deputados do Brasil",
            "source_url": "http://www2.camara.leg.br/transparencia/cota-para-exercicio-da-atividade-parlamentar/dados-abertos-cota-parlamentar"
        },
        {
            "author_name": "Álvaro Justen",
            "author_url": "https://twitter.com/turicas",
            "code_url": "https://github.com/turicas/transparencia-gov-br",
            "description": "Dados do Portal da Transparência do Governo Federal.",
            "id": "https://brasil.io/api/dataset/govbr/",
            "license_name": "Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)",
            "license_url": "https://creativecommons.org/licenses/by-sa/4.0/",
            "name": "Governo Federal",
            "slug": "govbr",
            "source_name": "Portal da Transparência do Governo Federal",
            "source_url": "http://transparencia.gov.br/"
        },
        {
            "author_name": "Álvaro Justen e dezenas de colaboradores",
            "author_url": "https://blog.brasil.io/2020/03/23/dados-coronavirus-por-municipio-mais-atualizados/",
            "code_url": "https://github.com/turicas/covid19-br",
            "description": "Boletins informativos e casos do coronavírus por município por dia",
            "id": "https://brasil.io/api/dataset/covid19/",
            "license_name": "Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)",
            "license_url": "https://creativecommons.org/licenses/by-sa/4.0/",
            "name": "COVID-19",
            "slug": "covid19",
            "source_name": "Secretarias de Saúde estaduais",
            "source_url": "https://docs.google.com/spreadsheets/d/1S77CvorwQripFZjlWTOZeBhK42rh3u57aRL1XZGhSdI/edit?usp=sharing"
        }
    ]
}
